config/routes.rb
Rails.application.routes.draw do
  get 'events/index'

  get 'events/show'
  devise_for :admins, :skip => [:registrations]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations' }

  devise_scope :user do
    get '/confirmation-getting-started' => 'registrations#getting_started', as: 'confirmation_getting_started'
  end

  get 'ratings/new'

  get 'ratings/answer'

  get 'ratings/edit'

  get 'ratings/show'

  get 'comments/new'

  get 'comments/answer'

  get 'comments/edit'

  get 'comments/destroy'

  get 'comments/show'

  get 'comments/index'

  get 'videographies/index'

  get 'videographies/new'

  get 'videographies/answer'

  get 'videographies/destroy'

  get 'videos/destroy'

  get 'videos/new'

  get 'videos/answer'

  get 'shootings/index'

  get 'shootings/show'

  get 'shootings/destroy'

  get 'shootings/edit'

  get 'shootings/new'

  get 'profiles/show'

  get 'profiles/edit'

  get 'profiles/update'

  get 'profiles/destroy'

  get 'portfolios/show'

  get 'portfolios/destroy'

  get 'portfolios/edit'

  get 'portfolios/update'

  get 'photos/destroy'

  get 'portfolios/index'

  get 'portfolios/show'

  get 'static_pages/index'

  get '/index' => redirect('/')

   root 'static_pages#index'

  resources :events, only: [:index, :show]
  resources :portfolios
  resources :photos, only: [:destroy, :new, :create]
  resources :videos, only: [:destroy, :new, :create]
  resources :profiles
  resources :shootings, :videographies
  resources :comments, only: [:new, :create, :destroy]
  resources :ratings, only: [:new, :create, :edit]
  match '/greeting', to: 'static_pages#greetings',     via: 'get', as: :greeting_user
  match '/catalog', to: 'static_pages#catalog',     via: 'get'
  match '/catalog', to: 'static_pages#catalog',     via: 'post'
  match '/about', to: 'static_pages#about',     via: 'get'
  match '/photofilter', to: 'static_pages#photofilter', via: 'post'
  match '/photofilter', to: 'static_pages#catalog', via: 'get'
  match '/videofilter', to: 'static_pages#videofilter', via: 'post'
  match '/videofilter', to: 'static_pages#catalog', via: 'get'
  match '/new_shooting', to: 'portfolios#new_shooting', via: 'post'
  match 'portfolios/ratings/onPluginClick', to: 'ratings#onPluginClick', via: 'post'
  match 'portfolios/ratings/get_rating_info', to: 'ratings#get_rating_info', via: 'post'
  match '/edit_avatar', to: 'profiles#edit_avatar',  via: 'get', as: :edit_avatar
  match '/update_avatar', to: 'profiles#update_avatar',  via: 'patch', as: :update_avatar
  match '/upload_image', to: 'photos#upload',  via: 'post', as: :upload_image

end

app/views/shared/_add_new_photo.erb
<script>
  var initDropZone = function () {
    var myDropzone = new Dropzone("div#place-for-drop", { url: "/upload_image", paramName: "photo[image]"});
    document.querySelector("div#place-for-drop").classList.add("dropzone");
    myDropzone.on('sending', function(file, xhr, formData){
      formData.append('photo[title]', 'Great Image');
      formData.append('photo[category]', '<%= @category %>');
    });

    myDropzone.on('success', function(file, data){
      var obj = $(data + '');
      obj.lightcase();
      $('.shooting-block#<%= @category %> .slider-container').slick('slickAdd',obj);
    });
  };
</script>



<div class='form-for-new-photo' id = "add_new_photo">
  <div style="color: white"> Перетащите фаши фотографии в область загрузки или кликните на область для выбора</div>
  <div id="place-for-drop"></div>

</div>

app/views/shared/_add_new_video.erb
<div class='form-for-new-video' id="add_new_video">
  <%= form_for @video, :html => {:multipart => true, :class => 'registration-box', :style => 'min-height:300px;'} do |f| %>
      <div class="register_field">
          <label> Название</label>
        <div class="register_field">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="register_field">
        <%= f.label 'URL видео:' %>

        <div class="register_label">
        <%= f.text_field :path %>
          </div>
      </div>
      <%= f.hidden_field :category, value: @category %>
      <div class="register_field" style="margin-top: 10px;">
      <%= f.submit "Добавить видео", class: "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/shared/_add_shooting.erb
<%
  categories = []
  current_user.shootings.each do |s|
    categories << s.category
  end
  categories = ApplicationHelper.get_photo_categories - ['Все'] - categories
%>

<div class="add-shooting" id="add-shooting">
  <%= form_for @shooting, :html => {:multipart => true, :class => 'registration-box'}, :method => 'post' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="category_and_price_field">
        <div class="register_field">
          <div class="register_label">
            <%= f.label 'Категория' %>
          </div>
          <div class="register_field small_mode">
            <%= f.select :category, options_for_select(categories),:html =>{class: 'register_field_select'}  %>
          </div>
        </div>
        <div class="register_field">
          <div class="register_label">
            <%= f.label 'Цена' %>
          </div>
          <div class="register_field small_mode">
            <%= f.number_field :price, class: 'register_field_price' %>
          </div>
        </div>

      </div>

      <div class="register_label">
        <%= f.label 'Авторское описание' %>
      </div>
      <div class="register_field">
        <%= f.text_area :description, class: 'register_field_description' %>
      </div>
      <div class="register_field">
        <%= f.submit "Добавить", class: "btn btn-primary" %>
      </div>

  <% end %>

</div>

app/views/shared/_add_videography.erb
<%
  categories = []
  current_user.videographies.each do |s|
     categories << s.category
   end
  categories = ApplicationHelper.get_video_categories - ['Все'] - categories
%>

<div class="add-videography" id="add-videography">
  <%= form_for @videography, :html => {:multipart => true, :class => 'registration-box'}, :method => 'post' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="category_and_price_field">
        <div class="register_field">
          <div class="register_label">
            <%= f.label 'Категория' %>
          </div>
          <div class="register_field small_mode">
            <%= f.select :category, options_for_select(categories),:html =>{class: 'register_field_select'}  %>
          </div>
        </div>
        <div class="register_field">
          <div class="register_label">
            <%= f.label 'Цена' %>
          </div>
          <div class="register_field small_mode">
            <%= f.number_field :price, class: 'register_field_price' %>
          </div>
        </div>

      </div>

      <div class="register_label">
        <%= f.label 'Авторское описание' %>
      </div>
      <div class="register_field">
        <%= f.text_area :description, class: 'register_field_description' %>
      </div>
      <div class="register_field">
        <%= f.submit "Добавить", class: "btn btn-primary" %>
      </div>

  <% end %>

</div>

app/views/shared/_append_photo.js.erb
$("<%= escape_javascript(render partial: 'photos/photo_preview') %>").appendTo('.shooting-block#<%= @photo.category.gsub(/\s+/, "") %>');

app/views/shared/_avatar_uploader.html.erb
<%= form_for @profile, :html => {:multipart => true} do |f| %>
    <p>
      <label>My Avatar</label>
      <%= image_tag(@user.avatar_url) if @user.avatar? %>
      <%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache %>
    </p>
<% end %>

app/views/shared/_better_header.html.erb
<script>
  $(window).on('resize', function () {
    $('header .menu').toggleClass('activated', false);
    $('header #profile-block-menu').toggleClass('activated', false);
  })
</script>

<%= puts onmain %>
<header class=<%= 'onmain' if onmain %> >
  <div class="menu-button" onclick="$(this).toggleClass('open');$('.menu').toggleClass('activated');">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
  </div>
  <div class="menu">
    <%= link_to "О нас", '/about', 'data-no-turbolink' => true %>
    <%= link_to "Контакты", '#' %>
    <%= link_to "На Главную", root_path, id: "hidden-main-link" %>
    <!--<%= link_to  "", root_path, id: 'logo' %>-->
    <a href="<%=root_path %>" id='logo'>
      <div class="header_decor_triangle"></div>
    </a>
    <%= link_to "Новости", events_index_path %>
  </div>

  <div class="personal-cabinet">
    <% if user_signed_in? %>
        <%= image_tag current_user.profile.avatar, class: "header-avatar", onerror:"this.style.display='none'" %>
        <%= link_to current_user.profile.name, current_user.profile, id: 'name_header_link' %>
        <div id="profile-block-menu-button" clicked="false" onclick="$('#profile-block-menu').toggleClass('activated')"></div>
    <% else %>
        <%= link_to "Войти", new_user_session_path %>
        <%= link_to "Регистрация", new_user_registration_path, id: 'sign_up_btn' %>
    <% end %>
    <div id="profile-block-menu">
      <% if user_signed_in? %>
          <%= link_to "Профиль", current_user.profile %>
          <% if current_user.operator? %>
              <%= link_to "Портфолио", current_user.portfolio %>
          <% end %>
          <%= link_to "Выйти", destroy_user_session_path, method: "delete" %>
      <% end %>
    </div>
  </div>
</header>
<div class=zaglushka></div>
<div id="line-with-logo">
</div>

 <!-- render 'shared/login_form' -->

app/views/shared/_event_summary.html.erb
<div class = "event-wrapper">
    <div class = 'event-text-block'>
        <div class = 'event-title'>
            <h2><%= event.title %></h2>
        </div>
        <div class = 'event-summary'>
            <%= event.summary %>
        </div>
        <div class = 'event-link-to-full'>
            <%= link_to 'ЧИТАТЬ >>', event %>
        </div>
    </div>
    <div class = 'event-image-block'>
        <%= image_tag event.image, class: 'event-image autosize-img' %>
    </div>
    <div class = 'event-type-block'>
      <div style="width:110px;">Новость</div>
    </div>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="header-section">
    <%= link_to "О нас", '/about', 'data-no-turbolink' => true %>
  </div>
  <div class="header-section">
  <%= link_to "Новости", events_index_path%>
</div>
  <div class="header-section" id="hidden-main-link">
    <%= link_to "На Главную", root_path%>
  </div>
  <%= link_to "", root_path, class: "header-section", id: 'logo' %>
  <div class=header-section>
    <%= link_to "Каталог", '/catalog','data-no-turbolink' => true %>
  </div>
  <div class="personal-cabinet header-section">
    <% if user_signed_in? %>
        <%= image_tag current_user.profile.avatar, class: "header-avatar", onerror:"this.style.display='none'" %>
        <%= link_to current_user.profile.name, current_user.profile, id: 'name_header_link' %>
        <div class="profile-block-header">
          <div id="profile-block-header-button" clicked="false" onclick="showMenu('profile-block-header-button','profile-block-header-menu')"></div>
        </div>
    <% else %>
        <%= link_to "Войти", new_user_session_path %>
        <%= link_to "Регистрация", new_user_registration_path, id: 'sign_up_btn' %>
    <% end %>
    <div id="profile-block-header-menu" class="header-section">
      <% if user_signed_in? %>
          <%= link_to "Профиль", current_user.profile %>
          <% if current_user.operator? %>
              <%= link_to "Портфолио", current_user.portfolio %>
          <% end %>
      <% end %>
      <%= link_to "Выйти", destroy_user_session_path, method: "delete" %>
    </div>
  </div>
</header>
<div class=zaglushka></div>
<div id="line-with-logo">
</div>
<div class="zaglushka zaglushka-add"></div>

 <!-- render 'shared/login_form' -->

app/views/shared/_home_video_section.html.erb
<script>
  $(function(){
    var slider2 = $('#slider2');
    var minCost2 = $('input#minCost2');
    var maxCost2 = $('input#maxCost2');
    slider2.slider({
      min: <%= prices[0] %>,
      max: <%= prices[1] %>,
      values: [<%= prices[0] %>,<%= prices[1] %>],
      range: true,
      animate: 'fast',
      stop: function(event, ui) {
        minCost2.val(slider2.slider("values",0));
        maxCost2.val(slider2.slider("values",1));
        $(".scrollable-sections-container").swipe('enable');
      },
      slide: function(event, ui){
        minCost2.val(slider2.slider("values",0));
        maxCost2.val(slider2.slider("values",1));
      },

      start: function(event, ui){
        $(".scrollable-sections-container").swipe('disable');
      }
    });

    minCost2.on('input', function(){
      var value1= minCost2.val();
      var value2= maxCost2.val();
      if(parseInt(value1) > parseInt(value2)){
        value1 = value2;
        minCost2.val(value1);
      }
      slider2.slider("values",0,value1);
    });

    maxCost2.on('input', function(){

      var value1=minCost2.val();
      var value2=maxCost2.val();
      if (value2 > <%= prices[1] %>) { value2 = <%= prices[1] %>; maxCost2.val(<%= prices[1] %>)}
      if(parseInt(value1) > parseInt(value2)){
        value2 = value1;
        maxCost2.val(value2);
      }
      slider2.slider("values",0,value2);
    });
  });

 </script>


<!--------СЛАЙД 2-------------->

<div id = "videohome" class="scrollable-section">
  <div class = transparent-block300></div>
  <div id="videoslide" class = "whitestripe active">
    <h1>- Видеосъемка -</h1>
    <%= form_tag("/catalog", method: "get", id: 'video_filter_form') do %>
        <div class = "slider-wrapper">
          <h2>средняя стоимость за час работы</h2>
          <input name="filter[price[min]" class = "slider-price-cell cell-min" type="number" min="0" max="100000" id="minCost2" value=<%= prices[0] %>>
          <input name = 'filter[price[max]' class = "slider-price-cell cell-max" type="number" min="0" max="100000" id="maxCost2" value=<%= prices[1] %>>
          <div id="slider2"></div>
          <%= hidden_field('filter', 'area', {id: 'video_area', value: 'Видеосъемка'}) %>
          <%= hidden_field('filter', 'category', {id: 'video_category_field', value: 'TFP'}) %>
          <div class="two-buttons-adaptive-pane">
            <%= submit_tag 'ИСКАТЬ', class:"btn-search", onclick: "showFilter(); return false;" %>
            <div class="swap-section" onclick="swipeToPhoto();">
              <div class="swap-section-button"></div>
              <div>К ФОТО</div>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <div id="videoslide-filters" class = "whitestripe">
    <div class = "filter-and-controls-section">
      <div class="filter-section-back-step">
        К ЦЕНЕ
        <div class="filter-section-back-step-button" onclick="showPrice()">
        </div>
      </div>
      <div class = "filter-section">
        <a class="filter-section-item"  ontouchstart="$(this).toggleClass('hover');" onclick="setAndSubmit('#video_filter_form', '#video_category_field', 'Клипы')">
          <div class="filter-section-item-flipper">
            <div class="filter-section-item-flipper-front" id="videofilter-item-front-1"></div>
            <div class="filter-section-item-flipper-back">Клипы</div>
          </div>
        </a>
        <a class="filter-section-item" ontouchstart="$(this).toggleClass('hover');" onclick="setAndSubmit('#video_filter_form', '#video_category_field', 'Творческие')">
          <div class="filter-section-item-flipper">
            <div class="filter-section-item-flipper-front" id="videofilter-item-front-2"></div>
            <div class="filter-section-item-flipper-back">Творческие</div>
          </div>
        </a>
        <a class="filter-section-item" ontouchstart="$(this).toggleClass('hover');" onclick="setAndSubmit('#video_filter_form', '#video_category_field', 'Свадьбы')">
          <div class="filter-section-item-flipper">
            <div class="filter-section-item-flipper-front" id="videofilter-item-front-3"></div>
            <div class="filter-section-item-flipper-back">Свадьбы</div>
          </div>
        </a>
        <a class="filter-section-item" ontouchstart="$(this).toggleClass('hover');" onclick="setAndSubmit('#video_filter_form', '#video_category_field', 'Праздники')">
          <div class="filter-section-item-flipper">
            <div class="filter-section-item-flipper-front" id="videofilter-item-front-4"></div>
            <div class="filter-section-item-flipper-back" >Праздники</div>
          </div>
        </a>
        <a class="filter-section-item" ontouchstart="$(this).toggleClass('hover');" onclick="setAndSubmit('#video_filter_form', '#video_category_field', 'Вечеринки')">
          <div class="filter-section-item-flipper">
            <div class="filter-section-item-flipper-front" id="videofilter-item-front-5"></div>
            <div class="filter-section-item-flipper-back" >Вечеринки</div>
          </div>
        </a>
        <a class="filter-section-item" ontouchstart="$(this).toggleClass('hover');" onclick="setAndSubmit('#video_filter_form', '#video_category_field', 'Love Story')">
          <div class="filter-section-item-flipper">
            <div class="filter-section-item-flipper-front" id="videofilter-item-front-6"></div>
            <div class="filter-section-item-flipper-back" >Love Story</div>
          </div>
        </a>
        <a class="filter-section-item" ontouchstart="$(this).toggleClass('hover');" onclick="setAndSubmit('#video_filter_form', '#video_category_field', 'Коммерческие')">
          <div class="filter-section-item-flipper">
            <div class="filter-section-item-flipper-front" id="videofilter-item-front-7"></div>
            <div class="filter-section-item-flipper-back">Коммерческие</div>
          </div>
        </a>
        <a class="filter-section-item" ontouchstart="$(this).toggleClass('hover');" onclick="setAndSubmit('#video_filter_form', '#video_category_field', 'Другие')">
          <div class="filter-section-item-flipper">
            <div class="filter-section-item-flipper-front" id="videofilter-item-front-8"></div>
            <div class="filter-section-item-flipper-back" >Другие</div>
          </div>
        </a>

        <a class="filter-section-item" ontouchstart="$(this).toggleClass('hover');" onclick="setAndSubmit('#video_filter_form', '#video_category_field', 'Motion Design')">
          <div class="filter-section-item-flipper">
            <div class="filter-section-item-flipper-front" id="videofilter-item-front-9"></div>
            <div class="filter-section-item-flipper-back" >Motion Design</div>
          </div>
        </a>
      </div>
      <div class="filter-section-next-step">
      </div>
    </div>
  </div>

</div>

app/views/shared/_login_form.html.erb
<div id="login-form" class="registration-box" style="display: none">
  <%= form_for :session, url: sessions_path, :html => {:class => 'registration-box-fields-wrapper'}  do |f| %>
      <div class = "full-row-field form-header"> АВТОРИЗАЦИЯ </div>
        <div class="register_field">
          <%= f.text_field :email, :placeholder => 'Логин' %>
          </div>
        <div class="register_field">
          <%= f.password_field :password, :placeholder => 'Пароль' %>
        </div>
          <div class="full-row-field form-submit">
            <%= f.submit "ВОЙТИ", class: "form-submit-btn" %>
          </div>
          <div class="full-row-field">
            <%= link_to "Зарегистрируйся прямо сейчас!", signup_path, remote: true %>
          </div>
  <% end %>
</div>

app/views/shared/_registration_form.erb
<div id="signup-form" class="registration-box" style="display: none">
  <%= form_tag users_path, method: 'post' , :html => {:multipart => true, :class => 'registration-box-fields-wrapper'}, remote: true do |f| %>
      <div class="full-row-field form-header"> БЫСТРАЯ РЕГИСТРАЦИЯ</div>
      <div class="register_field">
        <%= text_field_tag 'user[email]', nil ,:placeholder => 'Ваш E-Mail' %>
      </div>
      <div class="register_field">
        <%= password_field_tag 'user[password]', nil ,:placeholder => 'Ваш пароль' %>
      </div>
      <div class="register_field">
        <%= password_field_tag 'user[password_confirmation]', nil ,:placeholder => 'Повторите пароль' %>
      </div>
      <div class="full-row-field">
        <%= label_tag 'operator', 'Я оператор', {:class => "check-box-replace-button", :onclick => 'customCheckbox($(this))'} %>
      </div>
      <div class="register_field" style = "display:none" >
        <%= check_box 'user', 'operator', {id: 'operator-checkbox'}, 'true', 'false'   %>
      </div>
      <div class="full-row-field form-submit">
        <%= submit_tag "Продолжить", class: "form-submit-btn" %>
      </div>
  <% end %>
</div>

<script>
  var customCheckbox = function(author) {
    var checkbox = $('.register_field input[type=hidden]');
    if(checkbox.prop('value') == 'false'){
      checkbox.prop('value', 'true');
    }else{
      checkbox.prop('value', 'false');
    }
    $(author).toggleClass('custom-checkbox-checked');
  }
</script>

app/views/shared/_video.erb
<iframe width="100%" height="100%" src="http://www.youtube.com/embed/<%= id %>" frameborder="0" allowfullscreen></iframe>

app/views/shared/_videocatalog.html.erb
<% @result.each  do |videography| %>
    <div class = 'search-result-item'>
      <div class = 'photo-examples-block'>
        <% chosen = get_photos_by_category(videography.user.videos, videography)
           puts chosen.inspect
           counter = 0%>
        <% if chosen.length > 3 && !chosen.blank?
             (0..2).each do |video| %>
                <iframe width="200px" height="150px" src=<%=chosen[video].path%> frameborder="0" allowfullscreen class = 'video-in-item'></iframe>
            <% end %>
        <% else if chosen.length <= 3 && !chosen.blank?
                  (0..chosen.length-1).each do |video| %>
                    <iframe width="200px" height="150px" src=<%=chosen[video].path%> frameborder="0" allowfullscreen class = 'video-in-item'></iframe>
                <% end %>
            <% end %>
        <%end %>

      </div>
      <div class = 'about-author-block'>
        <div class = "author-info">
          <span class = 'name-of-author'><%= videography.user.profile.name %></span>
          <span class = 'name-of-author'><%= videography.user.profile.surname %></span>
        </div>
        <div class = "author-info">
          <%= link_to image_tag(videography.user.profile.avatar.thumb, class: 'avatar-photo-in-item'),videography.user.portfolio %>
          <span class = 'age-cell'><%= get_age(videography.user) %> лет</span>
        </div>
        <div class = "author-info">
          <span class = 'price-cell'><%= videography.price %>/час</span>
        </div>
      </div>
      <div class = 'photo-examples-block'>
        <% if chosen.length > 3 && !chosen.blank?
             (3..5).each do |video| %>
                <iframe width="200px" height="150px" src=<%=chosen[video].path%> frameborder="0" allowfullscreen class = 'video-in-item'></iframe>
            <% end %>
        <%end %>
      </div>
    </div>
<% end %>